#include "electric_relay_device.hpp"
#include "main.h"

ElectricRelay kER_BridgeA(ElectricRelay_BridgeA_GPIO_Port, ElectricRelay_BridgeA_Pin);
ElectricRelay kER_BridgeB(ElectricRelay_BridgeB_GPIO_Port, ElectricRelay_BridgeB_Pin);
ElectricRelay kER_LoadConnector(ElectricRelay_LoadConnector_GPIO_Port, ElectricRelay_LoadConnector_Pin);
ElectricRelay kER_GridConnector(ElectricRelay_GridConnector_GPIO_Port, ElectricRelay_GridConnector_Pin);
